### ISSUE TITLE
Help with Datadog Graph?

### ISSUE THREAD

**Issue by aviflax** [packetloop/datadog-agent-burrow#1]
Thanks so much for making this plugin available!

I think I have it working, but I’m getting a puzzling result from my Datadog graph — I’m subtracting the sum of the consumer offsets from the sum of the topic offsets and I’m getting negative results, between 0 and -2000.

Here’s a screenshot:

<img width="1107" alt="screen shot 2016-11-01 at 12 48 10" src="https://cloud.githubusercontent.com/assets/141844/19898250/a7cd6b74-a031-11e6-8f72-13eb3998aebb.png">

What am I doing wrong here?

**Comment by jgmchan** [comment]
Sorry @aviflax, missed this issue.

This issue is caused by fact that the topic and consumer offsets exposed in Burrow are actually per partition rather than for the entire topic.

I'm going to try and add a metric which contains the total topic offsets and total consumer offsets.

**Comment by aviflax** [comment]
No worries — thanks!!

**Comment by jgmchan** [comment]
https://github.com/packetloop/datadog-agent-burrow/pull/2 Should solve this problem.

Use `kafka.topic.offsets.total` and `kafka.consumer.offsets.total` for the graphs.

**Comment by aviflax** [comment]
Great! I'll try to review it soon, just in case that'd be helpful.

**Comment by rajesh054** [comment]
Hi @aviflax Can u tell me how u have integrated datadog with burrow to get kafka consumer metrics??
please help urgently

**Comment by jimymodi** [comment]
@rajesh054 were you able to integrate it ? how ?

**Comment by rajesh054** [comment]
@jimymodi i was not able to integrate it

**Comment by lenfree** [comment]
hi @rajesh054 @jimymodi ,you still having integration issue? If you do, please create a new issue so we can keep track on a separate thread. Thanks!
